spring:
  application:
    name: redis-service
  # 配置mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: 123456
  # 配置redis缓存
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 1000
    password:
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8088

mybatis:
  mapper-locations: mapper/*.xml
